language: rust
rust:
- stable
- beta
- nightly
script:
- env
- cargo build --verbose
- cargo test --verbose -- --nocapture
cache: cargo
env:
  global:
  - secure: Bw+iZQUE4vXef+TApvX37e7znQ3f2szjPOCSYLeWbVgNITkMuGhMEWC7Y80voG4iV79en5xq59DFP/yrGYPzNMkP/4H0X2MdHufzSs4vpR3KmzSmr+xrHHo3P9b9Jim/VBuvOUM7a7i8j5Iq3S/SmVRSTFxjxM4NrSgiTfSPUDgFDk4gbLLagkGsD1Nc6Ov/enKRd5XH3GfxsCgsDtIuhHjWBJO8H2kTfuJiiU3q10dHdoN9czN9CkC8z77UJpVHACJYH8DDF5X/yCP4+9qlVTWzCYgnWt6D19OYeETcKDI6kNa2N1thjvBBPTO4arSm/IwSCPae+PYs2h5b8a3IL/StVpJsA/NqnXqLCCnylex8Ole9jyeQLjz7uSp5E/3+It5v+JV/Bh+FgfALqX1MAsCa3I0c/yuOLR/ynLEQn3YQ2ZnsZs/+7FYP3PXF8HYJbYLkhenqlzs+3xmCCzDsmt+psY8nmJtCjtgi44/Dh5en/Gp9IPeXG9MLhEbi5a8SLdkhF3qbMsWa1LsHV9xmVBHrSE8NtPpFgtYdxEKKPPpC37/JoVBTubKFuaWn04LbEmlH/WvWTYLfphOhcNrXgLJSKwvsQlg7FWx47iM6zWF7XdCno0Ew3J1hf0OuSn5d8TMFzAk8ayrEYOUSHNfjm+VsRW+CUBcPBP8QQ4VZsAQ=
  - secure: MCFyAf0sVcYXgpKKxAPX0XJoAObZUernc/nMTzavDo39gf+sPW71A088YcoNWJnBuyKUl2GAi+dLTT70b+X7MHAXVq7f4xd8BrAjJ4OEY1v93T8rLpRn0s7VHPO70W9GEM/JLwbsZRh8U8DVeqYJlDgDmFvcDeuTSO4gX6ehOp2FXUx9rH5XW/IYgjaHHZfmflyPFcJUlMvD6TMSddrrX//AH1VTcaiBOuuPmt1nyGOHL4uqI8htYpkiQDqaqX4dQNMM88n8hk16D8UmdtQVwDTM0BkGJ6i6M9CLfPHKQmsXiKDp37jeueI2XMspbEAgin3AA3blTNaBTCsVK3o8v1oiNCw8k9l79O/A5lEF9GiL1e7MIFovcZp7pLmx1iVNbG2DtEVOrzx0ZeohxLwoAK8AYOEQgSq/gVvYr0wok1R04d368OlwyVf29CnBiv8pNRVAY7oNtXu5gdU68g+r09oljsEED+ce9xv3R0qUYalszebKHE0yqHOy+YgE/24c1u/4yAOLSgTipSPcCh/KxmWEEE6xH5KWGy327OJFUYwfdcJfxvHpUomhRprLK7m9Up9p89q9fZ7u+bBFC1dC/UX+zh/8pqYfzfjTmiXq8M9EGHo0SIp8RuBvNTFhBXTJRt9OnqJ2l6qKUKy0zqmGVud/GgnuaT0EqRu2hAB+5OE=
